// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXlCIb8T7Jg5EfzCO2bvn5ZJ4xW_GbOcU',
    appId: '1:375911628428:web:eac25e705885c17de345a9',
    messagingSenderId: '375911628428',
    projectId: 'voting-automation18',
    authDomain: 'voting-automation18.firebaseapp.com',
    storageBucket: 'voting-automation18.appspot.com',
    measurementId: 'G-ZHCENWQ2FG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuCOJsTlQxiTFVNxaKhoRgfC8wgXPhqs8',
    appId: '1:375911628428:android:1b50081e00dbce03e345a9',
    messagingSenderId: '375911628428',
    projectId: 'voting-automation18',
    storageBucket: 'voting-automation18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADAKA82k9U47JAjJF1llCUH0ay1ayUsFA',
    appId: '1:375911628428:ios:1877f8363dc787f4e345a9',
    messagingSenderId: '375911628428',
    projectId: 'voting-automation18',
    storageBucket: 'voting-automation18.appspot.com',
    iosBundleId: 'com.example.votingAutomation18',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADAKA82k9U47JAjJF1llCUH0ay1ayUsFA',
    appId: '1:375911628428:ios:1877f8363dc787f4e345a9',
    messagingSenderId: '375911628428',
    projectId: 'voting-automation18',
    storageBucket: 'voting-automation18.appspot.com',
    iosBundleId: 'com.example.votingAutomation18',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXlCIb8T7Jg5EfzCO2bvn5ZJ4xW_GbOcU',
    appId: '1:375911628428:web:c85555a26c24116ae345a9',
    messagingSenderId: '375911628428',
    projectId: 'voting-automation18',
    authDomain: 'voting-automation18.firebaseapp.com',
    storageBucket: 'voting-automation18.appspot.com',
    measurementId: 'G-SERHQ0ZD1W',
  );
}
