// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ✅ Add Firebase Config for Web
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your_web_api_key',
    appId: 'your_web_app_id',
    messagingSenderId: 'your_messaging_sender_id',
    projectId: 'premium-portal-451012-c0',
    storageBucket: 'premium-portal-451012-c0.appspot.com',
  );

  // ✅ Add Firebase Config for Android
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'your_android_api_key',
    appId: 'your_android_app_id',
    messagingSenderId: 'your_messaging_sender_id',
    projectId: 'premium-portal-451012-c0',
    storageBucket: 'premium-portal-451012-c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC_mWDnXY5Uv8tqEC9HUp8KagzeZxM6w4',
    appId: '1:918932427902:ios:6d0f47d19f7edbef17b42f',
    messagingSenderId: '918932427902',
    projectId: 'premium-portal-451012-c0',
    storageBucket: 'premium-portal-451012-c0.firebasestorage.app',
    iosBundleId: 'com.example.votingAutomation18',
  );

  // ✅ Firebase Config for iOS

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC_mWDnXY5Uv8tqEC9HUp8KagzeZxM6w4',
    appId: '1:918932427902:ios:6d0f47d19f7edbef17b42f',
    messagingSenderId: '918932427902',
    projectId: 'premium-portal-451012-c0',
    storageBucket: 'premium-portal-451012-c0.firebasestorage.app',
    iosBundleId: 'com.example.votingAutomation18',
  );

  // ✅ Firebase Config for macOS

  // ✅ Add Firebase Config for Windows (optional)
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your_windows_api_key',
    appId: 'your_windows_app_id',
    messagingSenderId: 'your_messaging_sender_id',
    projectId: 'premium-portal-451012-c0',
    storageBucket: 'premium-portal-451012-c0.appspot.com',
  );

  // ✅ Add Firebase Config for Linux (optional)
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'your_linux_api_key',
    appId: 'your_linux_app_id',
    messagingSenderId: 'your_messaging_sender_id',
    projectId: 'premium-portal-451012-c0',
    storageBucket: 'premium-portal-451012-c0.appspot.com',
  );
}